[package]
name = "mdutil-lib"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = "1.0.0-alpha.12"
regex = "1.9.3"
once_cell = "1.18.0"
anyhow = "1.0.75"
