[workspace]
resolver = "2"
members = [
    "mdutils",
    "mdmove",
    "mdsummary",
    "mdbook-replace",
]

[workspace.dependencies]
anyhow = "1.0.75"
clap = { version = "4.5.16", features = ["derive"] }
url = "2.5.2"
mdutils = { path = "./mdutils", version = "0.0.1" }
