[package]
name = "mdutils"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
once_cell = "1.18.0"
tree-sitter = "0.21.0"
tree-sitter-md = "0.2.3"
