[package]
name = "mdmove"
version = "0.0.1"
edition = "2021"

[dependencies]
mdutils = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
url = { workspace = true }
pathdiff = "0.2.1"
